### ISSUE TITLE
Self-post thumbnail issue

### ISSUE THREAD

**Issue by RobbyMeeker** [brian6932/Reddit-Carbon-Theme#1]
Hey, this theme has been working fantastically for a while now, but I think reddit may have changed something and now text post thumbnails look like this:
https://i.imgur.com/PVbaYtx.png
I'm wondering if anyone knows of a way to resolve this?

**Comment by brian6932** [comment]
Uhh I'll look into it

**Comment by brian6932** [comment]
I don't have this, you're on old reddit and using RES, correct? @RobbyMeeker 
![image_237](https://user-images.githubusercontent.com/18603393/167754268-98365efb-ad2a-4921-82bf-1098d09ccdd3.png)
[Make sure to disable subreddit styles, so there isn't anything conflicting with the userstyle.](https://www.wikihow.tech/Disable-Subreddit-Style-on-Reddit-PC-or-Mac)

**Comment by RobbyMeeker** [comment]
Yeah subreddit styles are disabled and RES is installed. It's weird since it was working fine just a few days ago. I'm not sure what has changed. I have tried disabling all of my extensions other than Stylus and RES, and still is not working correctly. Weird.

**Comment by brian6932** [comment]
@RobbyMeeker browser?

**Comment by brian6932** [comment]
Also do you have night mode enabled on RES?

**Comment by RobbyMeeker** [comment]
Chrome Version 101.0.4951.64 . RES I have tried with and without night mode, same issue on both modes.

**Comment by brian6932** [comment]
Cannot reproduce, does this happen in any other browsers?
If yes, can you try to test this in a [portable browser instance](https://portableapps.com/apps/internet/google_chrome_portable)
If no, it's prob an extension or config setting you have set.

**Comment by RobbyMeeker** [comment]
Just tried on a fresh install of firefox with only stylus installed, same issue. Has to be on my end. I appreciate the help regardless, thanks.

**Comment by brian6932** [comment]
I'll keep this issue open for now, it's always possible Reddit has some auto opt-in experiment or something.
