### ISSUE TITLE
Restore RES "+Shortcut" button in Subreddit sidebar

### ISSUE THREAD

**Issue by jedirulez** [brian6932/Reddit-Carbon-Theme#2]
Is it possible to restore the RES +shortcut button in the subreddit sidebar that adds shortcuts to the header? Or swap the +dashboard for +shortcut.
![chrome_ZCNVkTjSv6](https://user-images.githubusercontent.com/27040141/224612380-33d3360b-4538-47ff-91a2-5bef9521ed5c.png)
![chrome_dTl0dlp29O](https://user-images.githubusercontent.com/27040141/224612389-8ff19136-1c48-4081-b7ab-384f17d6286f.png)

**Comment by brian6932** [comment]
Done 👍
