### ISSUE TITLE
[Request] I've used your theme as a base for mine

### ISSUE THREAD

**Issue by misspent** [brian6932/Reddit-Carbon-Theme#3]
I've used your theme as a base for my theme and have expanded upon it rather extensively, and I'm curious if I can publish it on here and userstyles; if not, then it's all good, but I thought it's better to ask than not.

Example image:
![Reddit - Home Page](https://github.com/brian6932/Reddit-Carbon-Theme/assets/78914154/99d2248f-9762-4fff-a80f-636c20c7aa2f)

**Comment by brian6932** [comment]
You can fork it and use your own branch, if you want it merged, you can open a PR from that branch, I can take a look, and merge it if I like the changes

**Comment by misspent** [comment]
I doubt I'll go for a merge, as it has changed a fair bit, not just on the home page, and I'll more than likely list it on [this repo](https://github.com/misspent/Darkened-Stylus-Themes) like I did the others.
